spring:
  application:
    name: sazzler-api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sazzler-product-service
              uri: lb://sazzler-product-service
              predicates:
                - Path=/api/product/**
              filters:
                - StripPrefix=1

            - id: sazzler-order-service
              uri: lb://sazzler-order-service
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=1

            - id: sazzler-auth-service
              uri: lb://sazzler-auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1
server:
  port: 8080

jwt:
    secret: 27f9bcfc4523599275abbb317f7117e8e864e7f31c2198c45df93f6c2d1a9ce7
    expiration: 3600000 # (1 hour)

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: http://amodhyh:1234@localhost:8761/eureka/
